name: build

on:
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/jacoco.yml', 'pom.xml' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jacoco-java-maven:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package -Pcoverage

    - name: Generate JaCoCo badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true

    - name: Log coverage percentages to workflow output
      run: |
        echo "Total Coverage: ${{ steps.jacoco.outputs.coverage }}"
        echo "Branch Coverage: ${{ steps.jacoco.outputs.branches }}"
        echo "Instruction Coverage: ${{ steps.jacoco.outputs.instructionCoverage }}"
        echo "Line Coverage: ${{ steps.jacoco.outputs.lineCoverage }}"
        echo "Complexity Coverage: ${{ steps.jacoco.outputs.complexityCoverage }}"
        echo "Method Coverage: ${{ steps.jacoco.outputs.methodCoverage }}"
        echo "Class Coverage: ${{ steps.jacoco.outputs.classCoverage }}"

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Comment on PR with JaCoCo coverage summary
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        REPORT=$(<badges/coverage-summary.json)
        COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
        BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
        INSTRUCTIONS=$(jq -r '.instructionCoverage' <<< "$REPORT")%
        LINE=$(jq -r '.lineCoverage' <<< "$REPORT")%
        COMPLEXITY=$(jq -r '.complexityCoverage' <<< "$REPORT")%
        METHOD=$(jq -r '.methodCoverage' <<< "$REPORT")%
        CLASS=$(jq -r '.classCoverage' <<< "$REPORT")%
        NEWLINE=$'\n'
        BODY="## JaCoCo Test Coverage Summary${NEWLINE}"
        BODY="${BODY}* __Overall Coverage:__ ${COVERAGE}${NEWLINE}"
        BODY="${BODY}* __Branch Coverage:__ ${BRANCHES}${NEWLINE}"
        BODY="${BODY}* __Instruction Coverage:__ ${INSTRUCTIONS}${NEWLINE}"
        BODY="${BODY}* __Line Coverage:__ ${LINE}${NEWLINE}"
        BODY="${BODY}* __Complexity Coverage:__ ${COMPLEXITY}${NEWLINE}"
        BODY="${BODY}* __Method Coverage:__ ${METHOD}${NEWLINE}"
        BODY="${BODY}* __Class Coverage:__ ${CLASS}${NEWLINE}"
        gh pr comment ${{github.event.pull_request.number}} -b "${BODY}"
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
